### ISSUE TITLE
Labels of LAION-styles

### ISSUE THREAD

**Issue by vsahil** [learn2phoenix/CSD#1]
Hi Authors,

Great work! Congratulations! 
Is it possible to share the list of labels in the LAION-styles datasets (3840 tags from the paper)

Thank you so much

**Comment by learn2phoenix** [comment]
Thanks for your interest in our work. We are currently figuring out how to release anything related to LAION considering they pulled down the dataset. We will reach out to you shortly.

**Comment by learn2phoenix** [comment]
Thanks for your interest in our work. The tags have been uploaded as `laion-styles-subset-tags.txt` in the root folder

**Comment by vsahil** [comment]
thank you so much!
