### ISSUE TITLE
What do "content_output" and "style_output" mean?

### ISSUE THREAD

**Issue by eldercrow** [learn2phoenix/CSD#10]
https://github.com/learn2phoenix/CSD/blob/3a9df32605b869eceb704897839be80977a9f1ea/CSD/model.py#L110

If I understood your paper correctly, the goal of CSD is to measure style similarity between two images. However, while reviewing the code, I noticed that the function returns two outputs: content_output and style_output.

I have two questions regarding this:

 - What is the specific meaning of each output, content_output and style_output?
 - Which of these outputs should I use to measure style similarity between images?

**Comment by somepago** [comment]
"content_output" output was leftover from a failed experiment, please ignore that. 

"style_output" is the style feature and what the retrieval tasks are performed on.
