### ISSUE TITLE
List of the 96 artists

### ISSUE THREAD

**Issue by vsahil** [learn2phoenix/CSD#2]
Hi Authors,

I had a few more questions regarding your work:
1. How did you extract the names of the artists from the 80K stable diffusion prompts (https://huggingface.co/datasets/Gustavosta/Stable-Diffusion-Prompts) used in Section 7?
2. Is it possible to share the list of the 96 artists you used for the motivation section and the list of the 400 artists you used on Section 7? 

Thank you so much!

**Comment by learn2phoenix** [comment]
1. Most repeated artists. We also made sure that old artists were included too and we don't have density only on newer artists.
2. The 96 artists are mentioned in Section B of Appendix
3. The 400 artist list has been uploaded as `artists_400.txt` under root
