### ISSUE TITLE
evaluate error

### ISSUE THREAD

**Issue by whybfq** [learn2phoenix/CSD#4]
I generated the embeddings in /embeddings/csd_vit_large_wikiart_normal/1/database
![image](https://github.com/learn2phoenix/CSD/assets/9796567/8570b6e9-011f-412e-8de8-e689438f7a19)

`python search.py --mode artist --dataset wikiart --chunked --query-chunk-dir ./embeddings/csd_vit_large_wikiart_normal/1/database --database-chunk-dir ./embeddings/csd_vit_large_wikiart_normal/1/database --topk 1 10 100 1000 --method IP --data-dir ./dataset`

while got the error as below:
`asyncio - DEBUG - Using selector: EpollSelector
asyncio - DEBUG - Using selector: EpollSelector
search.embeddings - INFO - Consuming 0/1 chunks
search.embeddings - INFO - Finished reading chunks
Traceback (most recent call last):
  File "/home/hangyi/Downloads/sdAnalyze/CSD/search.py", line 165, in <module>
    main()
  File "/home/hangyi/Downloads/sdAnalyze/CSD/search.py", line 80, in main
    val_embeddings = Embeddings(args.emb_dir, args.database_chunk_dir,
  File "/home/hangyi/Downloads/sdAnalyze/CSD/search/embeddings.py", line 21, in __init__
    self.embedding_files = list(map(lambda x: osp.join(data_dir, x), files))
  File "/home/hangyi/Downloads/sdAnalyze/CSD/search/embeddings.py", line 21, in <lambda>
    self.embedding_files = list(map(lambda x: osp.join(data_dir, x), files))
  File "/home/hangyi/anaconda3/envs/style/lib/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
`

Any suggestions, thanks

**Comment by crested-ezios** [comment]
Add argument `--emb-dir ./embeddings` after your evaluate command to solve `'NoneType'` problem. 

Another noteworthy thing is that the place for two chunks usually are different, for example: 
```
--query-chunk-dir ./embeddings/csd_vit_large_wikiart_normal/1/query
--database-chunk-dir ./embeddings/csd_vit_large_wikiart_normal/1/database
```

**Comment by learn2phoenix** [comment]
@whybfq  I hope it worked after the suggestion by @crested-ezios , thanks @crested-ezios

**Comment by learn2phoenix** [comment]
closing this, please reopen if facing issues.
